package math3d

object Vec3
{
  def apply(s: Float): Vec3 = Vec3(s, s, s)
  def apply(v: Vec3): Vec3 = Vec3(v.x, v.y, v.z)
  def apply(v: Vec4): Vec3 = Vec3(v.x, v.y, v.z)
  def apply(v: Vec2, s: Float): Vec3 = Vec3(v.x, v.y, s)
}

case class Vec3(x: Float, y: Float, z: Float)
{
  def toArray = Array(x, y, z)

  def apply(index: Int): Float = index match
  {
    case 0 ⇒ x
    case 1 ⇒ y
    case 2 ⇒ z
    case _ ⇒ IndexError(index)
  }

  //scala operators
  def +(s: Float) = Vec3(x + s, y + s, z + s)
  def -(s: Float) = Vec3(x - s, y - s, z - s)
  def *(s: Float) = Vec3(x * s, y * s, z * s)
  def /(s: Float) = Vec3(x / s, y / s, z / s)

  //piecewise operators
  def +(v: Vec3) = Vec3(x + v.x, y + v.y, z + v.z)
  def -(v: Vec3) = Vec3(x - v.x, y - v.y, z - v.z)
  def *(v: Vec3) = Vec3(x * v.x, y * v.y, z * v.z)
  def /(v: Vec3) = Vec3(x / v.x, y / v.y, z / v.z)

  //swizzle
  def xx = Vec2(x, x)
  def xy = Vec2(x, y)
  def xz = Vec2(x, z)
  def yx = Vec2(y, x)
  def yy = Vec2(y, y)
  def yz = Vec2(y, z)
  def zx = Vec2(z, x)
  def zy = Vec2(z, y)
  def zz = Vec2(z, z)
  def xxx = Vec3(x, x, x)
  def xxy = Vec3(x, x, y)
  def xxz = Vec3(x, x, z)
  def xyx = Vec3(x, y, x)
  def xyy = Vec3(x, y, y)
  def xyz = Vec3(x, y, z)
  def xzx = Vec3(x, z, x)
  def xzy = Vec3(x, z, y)
  def xzz = Vec3(x, z, z)
  def yxx = Vec3(y, x, x)
  def yxy = Vec3(y, x, y)
  def yxz = Vec3(y, x, z)
  def yyx = Vec3(y, y, x)
  def yyy = Vec3(y, y, y)
  def yyz = Vec3(y, y, z)
  def yzx = Vec3(y, z, x)
  def yzy = Vec3(y, z, y)
  def yzz = Vec3(y, z, z)
  def zxx = Vec3(z, x, x)
  def zxy = Vec3(z, x, y)
  def zxz = Vec3(z, x, z)
  def zyx = Vec3(z, y, x)
  def zyy = Vec3(z, y, y)
  def zyz = Vec3(z, y, z)
  def zzx = Vec3(z, z, x)
  def zzy = Vec3(z, z, y)
  def zzz = Vec3(z, z, z)
  def xxxx = Vec4(x, x, x, x)
  def xxxy = Vec4(x, x, x, y)
  def xxxz = Vec4(x, x, x, z)
  def xxyx = Vec4(x, x, y, x)
  def xxyy = Vec4(x, x, y, y)
  def xxyz = Vec4(x, x, y, z)
  def xxzx = Vec4(x, x, z, x)
  def xxzy = Vec4(x, x, z, y)
  def xxzz = Vec4(x, x, z, z)
  def xyxx = Vec4(x, y, x, x)
  def xyxy = Vec4(x, y, x, y)
  def xyxz = Vec4(x, y, x, z)
  def xyyx = Vec4(x, y, y, x)
  def xyyy = Vec4(x, y, y, y)
  def xyyz = Vec4(x, y, y, z)
  def xyzx = Vec4(x, y, z, x)
  def xyzy = Vec4(x, y, z, y)
  def xyzz = Vec4(x, y, z, z)
  def xzxx = Vec4(x, z, x, x)
  def xzxy = Vec4(x, z, x, y)
  def xzxz = Vec4(x, z, x, z)
  def xzyx = Vec4(x, z, y, x)
  def xzyy = Vec4(x, z, y, y)
  def xzyz = Vec4(x, z, y, z)
  def xzzx = Vec4(x, z, z, x)
  def xzzy = Vec4(x, z, z, y)
  def xzzz = Vec4(x, z, z, z)
  def yxxx = Vec4(y, x, x, x)
  def yxxy = Vec4(y, x, x, y)
  def yxxz = Vec4(y, x, x, z)
  def yxyx = Vec4(y, x, y, x)
  def yxyy = Vec4(y, x, y, y)
  def yxyz = Vec4(y, x, y, z)
  def yxzx = Vec4(y, x, z, x)
  def yxzy = Vec4(y, x, z, y)
  def yxzz = Vec4(y, x, z, z)
  def yyxx = Vec4(y, y, x, x)
  def yyxy = Vec4(y, y, x, y)
  def yyxz = Vec4(y, y, x, z)
  def yyyx = Vec4(y, y, y, x)
  def yyyy = Vec4(y, y, y, y)
  def yyyz = Vec4(y, y, y, z)
  def yyzx = Vec4(y, y, z, x)
  def yyzy = Vec4(y, y, z, y)
  def yyzz = Vec4(y, y, z, z)
  def yzxx = Vec4(y, z, x, x)
  def yzxy = Vec4(y, z, x, y)
  def yzxz = Vec4(y, z, x, z)
  def yzyx = Vec4(y, z, y, x)
  def yzyy = Vec4(y, z, y, y)
  def yzyz = Vec4(y, z, y, z)
  def yzzx = Vec4(y, z, z, x)
  def yzzy = Vec4(y, z, z, y)
  def yzzz = Vec4(y, z, z, z)
  def zxxx = Vec4(z, x, x, x)
  def zxxy = Vec4(z, x, x, y)
  def zxxz = Vec4(z, x, x, z)
  def zxyx = Vec4(z, x, y, x)
  def zxyy = Vec4(z, x, y, y)
  def zxyz = Vec4(z, x, y, z)
  def zxzx = Vec4(z, x, z, x)
  def zxzy = Vec4(z, x, z, y)
  def zxzz = Vec4(z, x, z, z)
  def zyxx = Vec4(z, y, x, x)
  def zyxy = Vec4(z, y, x, y)
  def zyxz = Vec4(z, y, x, z)
  def zyyx = Vec4(z, y, y, x)
  def zyyy = Vec4(z, y, y, y)
  def zyyz = Vec4(z, y, y, z)
  def zyzx = Vec4(z, y, z, x)
  def zyzy = Vec4(z, y, z, y)
  def zyzz = Vec4(z, y, z, z)
  def zzxx = Vec4(z, z, x, x)
  def zzxy = Vec4(z, z, x, y)
  def zzxz = Vec4(z, z, x, z)
  def zzyx = Vec4(z, z, y, x)
  def zzyy = Vec4(z, z, y, y)
  def zzyz = Vec4(z, z, y, z)
  def zzzx = Vec4(z, z, z, x)
  def zzzy = Vec4(z, z, z, y)
  def zzzz = Vec4(z, z, z, z)
}
